language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-go-appengine' ]; then cd .. && eval "mv $currentfolder generator-go-appengine" && cd generator-go-appengine; fi

